import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
//import { useRouter } from "next/router";
import url1 from "../assets/Karen.png";
import styles from "@/styles";
import { useGlobalContext } from "../context";

export default function Home() {
  const { contract, walletAddress, collections } = useGlobalContext();
  //console.log("co", collections);

  // function getRows(_collectionsArr) {
  //   const _rows = [];
  //   for (let i = 0; i < _collectionsArr.length; i++) {
  //     let obj = {};
  //     obj.key = `${i + 1}`;
  //     obj.collection = collections[i].name;
  //     obj.by = collections[i].team;
  //     obj.floorPrice = "0.01 ETH";
  //     obj.supply = collections[i].supply;
  //     _rows.push(obj);
  //   }
  //   //console.log("chi", _rows);
  //   return _rows;
  // }

  //const rows = getRows(collections);
  // console.log("r", rows);

  const rows = [
    {
      key: "1",
      collection: "Friends",
      by: "NOZO_ART",
      floorPrice: "0.01 ETH",
      supply: "10",
    },
    {
      key: "2",
      collection: "Bored Kids",
      by: "NOZO_ART",
      floorPrice: "0.01 ETH",
      supply: "100",
    },
    {
      key: "3",
      collection: "Crypto Robots",
      by: "COOLDAD",
      floorPrice: "0.01 ETH",
      supply: "50",
    },
  ];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/nft.png" />
      </Head>

      <div className={`${styles.pageContainer} ${styles.homePageContainer}`}>
        <div className={styles.homeCollectionContainer}>
          <div className={styles.homeBigTextContainer}>
            <p className={styles.formTextBig}>Our Collections</p>
          </div>
          <div className={styles.homeCollectionTable} role="table">
            <div className={styles.homeCollectionHeadRow}>
              <div className={styles.homeCollectionRowItemBig}>Collection</div>
              <div className={styles.homeCollectionRowItem}>By</div>
              <div className={styles.homeCollectionRowItem}>Floor Price</div>
              <div className={styles.homeCollectionRowItem}>Supply</div>
            </div>
            {rows.map((row, id) => (
              <Link
                key={id}
                className={styles.homeCollectionRow}
                // href={{
                //   pathname: "/listings/[collection]",
                //   query: { collection: `${row.collection}` },
                // }}
                href="/listings"
                //href={`/listings/${row.collection}`}
              >
                <div className={styles.homeCollectionRowItem}>
                  {row.collection}
                </div>
                <div className={styles.homeCollectionRowItem}>
                  <Image
                    src={url1}
                    alt="collection image"
                    className={styles.homeCollectionImg}
                  />
                </div>
                <div className={styles.homeCollectionRowItem}>{row.by}</div>
                <div className={styles.homeCollectionRowItem}>
                  {row.floorPrice}
                </div>
                <div className={styles.homeCollectionRowItem}>{row.supply}</div>
              </Link>
            ))}
          </div>
        </div>
      </div>
    </>
  );
}
