import Head from "next/head";

import styles from "@/styles";
import { useGlobalContext } from "../context";
import { useSubgraph } from "@/hooks/subgraph";
import CollectionRow from "../components/CollectionRow";

export default function Home() {
  const { loading, error, data } = useSubgraph();

  const collectionsArr = data ? data.createdCollections : null;

  // if (data) {
  //   console.log("data", data.createdCollections);
  // }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/nft.png" />
      </Head>

      <div className={`${styles.pageContainer} ${styles.homePageContainer}`}>
        <div className={styles.homeCollectionContainer}>
          <div className={styles.homeBigTextContainer}>
            <p className={styles.formTextBig}>Our Collections</p>
          </div>
          <div className={styles.homeCollectionTable} role="table">
            <div className={styles.homeCollectionHeadRow}>
              <div className={styles.homeCollectionRowItemBig}>Collection</div>
              <div className={styles.homeCollectionRowItem}>By</div>
              <div className={styles.homeCollectionRowItem}>Floor Price</div>
              <div className={styles.homeCollectionRowItem}>Supply</div>
            </div>

            {loading ? (
              <div>Loading...</div>
            ) : !collectionsArr ? (
              <div>No Collections</div>
            ) : (
              collectionsArr.map((collection, id) => (
                <CollectionRow key={id} collection={collection} />
              ))
            )}
          </div>
        </div>
      </div>
    </>
  );
}
